### ISSUE TITLE
موسم کی مدت

### ISSUE THREAD

**Issue by AzharInam** [julienmalard/Tinamit#12]
ربی (موسم سرما) کا موسم نومبر میں شروع ہوگا اور اپریل میں ختم ہوجائے گا. جبکہ خريف (موسم گرما) کا موسم مئی میں شروع ہوگا اور  اکتوبر میں ختم ہوجائے گا۔ اس کے ليے نمونے ميں تصيح کی ضرورت ہے۔

**Comment by julienmalard** [comment]
Por favor escribe en español o en su idioma. ¡Gracias!

**Comment by julienmalard** [comment]
میرا جیال میں نیا تنامیت میں ٹھیک ہو گ‏ئا۔ اگر نہیں مہربانی کرکے اسکو یہاں بتا دیجیئے۔
