### ISSUE TITLE
اوسط سالانہ بارش

### ISSUE THREAD

**Issue by AzharInam** [julienmalard/Tinamit#13]
علاقے میں اوسط سالانہ بارش 200 سے 400 ملی میٹر تک ہونا چاہئے. ربی اوسط = 80-90 ملی میٹر اور خريف اوسط = 210-250 ملی میٹر. فی الحال، ماڈل متوقع اوسط سے ذيادہ بارش دے رھا  ہے.

**Comment by julienmalard** [comment]
Por favor escribe en español o en su idioma. ¡Gracias!

**Comment by julienmalard** [comment]
Parece arreglado ahora.
