### ISSUE TITLE
تقدير کےمتغيرات

### ISSUE THREAD

**Issue by AzharInam** [julienmalard/Tinamit#14]
تقدير ميں سورج کی روشنی، کم سے کم اور ذيادہ سے ذيادہ درجہ حرارت کے متغيرات کو شامل کيا جائے۔

**Comment by julienmalard** [comment]
Por favor escribe en español o en su idioma. ¡Gracias!

**Comment by julienmalard** [comment]
تقدیر میں پہلا سے ہی شامل کی گئے ہیں۔ سرف ساحسماڈ کی جلد میں جوڑنی ہیے۔

**Comment by julienmalard** [comment]
Arreglado. سحی ہو گئی۔
