### ISSUE TITLE
Tengo problemas con el uso de la Interfaz de Tinamit en Spider (Python 3.6) 

### ISSUE THREAD

**Issue by andiefajardo** [julienmalard/Tinamit#20]
**Describe el error**
Intenté abrir el GUI, sin embargo no me fue posible. El paper dice que necesito Python 3.5+ y  lo he descargado, pero sigue sin poderme abrirme.
He intentado instalar en la consola lo siguiente:

pip install git+git://github.com/julienmalard/tinamit.git@master

```
The following command must be run outside of the IPython shell:

    $ pip install git+git://github.com/julienmalard/tinamit.git@master

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/
```
**Para reproducirlo**
Si lo encontraste con el IGU:
* La secuencia de botones que empujaste

Si lo encontraste con el IPA:
* ```Una copia del código que llegó al error.```

En ambos casos:
No me

**Información adicional**
 - Versión de Python - Spider (Python 3.6)
 - Versión de Tinamït [2.00 segun la documentacion descarga.]

**Comment by julienmalard** [comment]
Hola,

Aquí veo dos problemas. El primero es que `pip ...` se debe ejecutar no en la consola Python, sino la línea de comandos (`start -> lînea de comandos`).

El segundo es que en Windows, hay un error en Python que hace que `pip install ...` no funciona para programas que no están escritos en inglés (yo sé). (Propuse una [corrección](https://github.com/python/cpython/pull/8799#ref-commit-77b92b1) para Python que ya aceptaron, pero mientras lo incluyen en la próxima publicación de Python desafortunademente tendremos que instalarlo manualmente.) Por eso tendrías que seguir el proceso siguiente:

Solución temporaria para Windows (felices sean los que tengan Linux):
1. Instalar [Git para Windows](https://git-scm.com/download/win), si no lo tienes ya.
2. En la **línea de comandos**, mandar el siguiente:
```
git clone https://github.com/julienmalard/Taqdir.git
cd taqdir
python setup.py -q install
cd ..
git clone https://github.com/julienmalard/Tinamit.git
cd tinamit
python setup.py -q install
```

Notar que todos los usuarios de Python en Windows también tendrán que instalar manualmente todos los requisitos para Tinamït (Numpy, SciPy, Matplotlib, Pandas, y Theano en el mismo orden); si no los tienes ya recomiendo que los descargues de [aquí](https://www.lfd.uci.edu/~gohlke/pythonlibs/); después los puedes instalar con `pip install C:\camino\hacia\mis\descargas\nombre_del_paquete.whl`.

¡Cualquier duda sigamos la conversación aquí!
-Julien

**Comment by andiefajardo** [comment]
Hola Julien!
Estoy corriendo el codigo en la linea de comandos, pero me sale un error en la linea "python setup.py -q install"
![image](https://user-images.githubusercontent.com/42176733/45809451-7b205e00-bcc8-11e8-9576-7cf13bede4e6.png)
Sabes a que se debe?

**Comment by andiefajardo** [comment]
Hola! nuevamente
decidi instalar PyCharm para trabajar con el codigo de Tinamit. He intentado correr el GUI y me aparece el siguiente error

![image](https://user-images.githubusercontent.com/42176733/45814304-7e6e1680-bcd5-11e8-9d46-fca5400d88e1.png)

Como usuario de Windows he pensado que no tengo los paquetes requeridos por Tinamit, pero solo tuve que instalar Theano desde el Project Interpreter, los demas ya estaban, como por ejemplo numpy

![image](https://user-images.githubusercontent.com/42176733/45814357-a8bfd400-bcd5-11e8-92e7-abd01b08e66c.png)

Los anteriores pasos que me has comentado, ya lo he realizado entonces por eso no se a que se deba este error.

**Comment by julienmalard** [comment]
Hola,

Los mensajes te avisan de los paquetes que te faltan para instalar / usar Tinamït. Por ejemplo, tienes que hacer un `pip install polib` antes de instalar y después un `pip install xarray`. También los puedes instalar todos automáticamente desde el directorio Tinamït en la línea de comandos con un `pip install -r requirements.txt`. Después de eso debería funcionar `python setup.py install`.

No sé si Tinamït funciona con Anaconda, en general recomendamos la distribución general de Python pero si te funciona perfecto. :)

¡Allí me avisas!
-Julien

**Comment by andiefajardo** [comment]
Hola! 
Me recomiendas usar para instalar las librerias la linea de comandos de la distribucion general de Python y trabajar en PyCharm si necesito trabajar en el codigo? Es que ahora no se donde deba realizar esto...

**Comment by julienmalard** [comment]
Hola,

Lo que voy a discutir aquí trata más de Python en general y no de Tinamït. Pero visto que probablemente será de interés para la mayoría de los usuarios de Tinamït nuevos en Python pienso que es relevante discutirlo aquí.

1. La primera cosa es que **cada versión** de Python queda separada. Fuertement recomiendo que escoges una (Anaconda o estándar) y que quedes con ella, y que si cambias de opinión desinstales la anterior completamente antes de instalar nueva versión. Sino, es muy posible que termines con la mitad de los requísitos instalados en una versión y la otra mitad en otra, con ninguna que funciona.

2. La línea de comandos es una cosa própia a Windows, no a Python. Cuando haces `pip install...`, se debe hacer en la línea de comandos porque éste es un comando de Windows ("llamar el programa pip que fue instalado con Python"), y no una comanda en lenguaje Python. Si necesitas trabajar con código Python, allí sí tienes que hacerlo por editar los archivos Python en PyCharm (o Spyder, etc.). Nota también que PyCharm tiene una "terminal" que es la _misma cosa_ que la línea de comandos de Windows, y que tiene un "Python console" que es la _misma cosa_ que la consola Python que encuentras en menú "Start" de Windows. Así que puedes hacer todo desde PyCharm si te dice.

Allí me avisas si decides seguir con Anaconda o con Python estándar y si tienes preguntas con la instalación.

Saludos,
Julien

**Comment by andiefajardo** [comment]
Hola! Desinstale todo y lo volvi hacer y quiero saber si los setup.py se deben correr desde el comand line porque por alguna razon solo se abren en pycharm, pero no se si yo misma los debo correr. Me aparece esto. Ya instale todos los paquetes que se requieren.

![grafik](https://user-images.githubusercontent.com/42176733/47236712-498cd680-d3dd-11e8-93c7-e5fadcc3eac5.png)

**Comment by julienmalard** [comment]
Hola,

Correcto, para los setup.py hay que correrlos desde la terminal. Debes navigar hacia la carpeta que contiene el archivo setup.py de taqdir y después hacer `python setup.py develop`. Después naviga hacia la carpeta con el setup.py de tinamït y haz lo mismo.

Solo para confirmar, ¿cuáles otros paquetes instalaste y de cuál fuente? Al hecho, ¿estás utilizando Anaconda o Python3.7 estándar al final? 

Hasta pronto,
Julien

**Comment by andiefajardo** [comment]
Estos son los paquetes que tengo instalados.
He desinstalado Anaconda y las otrs extensiones que tenia de Python e instale finalmente Python 3.7 y lo estoy usando en Pycharm.
He intentando correr el comando python setup.py develop en la terminal de Pycharm y tengo este error
![grafik](https://user-images.githubusercontent.com/42176733/47264259-9c68aa00-d513-11e8-9fac-6d0392385ca0.png)

Ahora en verdad no se que estare haciendo mal....


![grafik](https://user-images.githubusercontent.com/42176733/47259353-d8b2f080-d4a8-11e8-8f47-1cd046992012.png)

**Comment by andiefajardo** [comment]
Hola!
Lo intente  setup.py en el terminal sin la palabra "python" para ambas carpetas
![grafik](https://user-images.githubusercontent.com/42176733/47264446-eeabca00-d517-11e8-9419-fde4dc2505ea.png)

Despues de hacer esto, ya en teoria todo deberia funcionar o debo hacer otro paso? y no entiendo porque me aparece error cuando digo "python" en la terminal

**Comment by julienmalard** [comment]
Hola,

1. No sé por qué no te está dando error sin el `python`, pero debería ser imposible sin ello. No está funcionando la comanda `python` porque Windows no sabe dónde lo instalaste. Tienes que ir a mi compu (cliquea de derecha), `propiedades`, `avanzadas`, `variables de entorno` y agregar la dirección de tu instalación de Python (`C:\Users\Andrea Catalina\Local\Programas\Python\Python37-32` al variable `PATH`). Para más detalles ver [aquí](https://medium.com/@01luisrene/como-agregar-variables-de-entorno-s-o-windows-10-e7f38851f11f).
2. Después reinicializa PyCharm y díme si funciona la comanda de instalación. No se te olvide hacer `taqdir` antes de `tinamit`.
3. Mirando tu lista de paquetes instalados, veo que numpy no está instalado con mkl. ¿Cómo instalaste los requísitos? (¡Me sorprende que lo lograste porque en general requiere el uso de `python` o `pip` en la terminal!)

Allí me avisas,
Julien

**Comment by julienmalard** [comment]
¿Sería que ya se arregló? Si es el caso favor confirma y marcaré este reporto como resuelto. ¡Gracias!

**Comment by julienmalard** [comment]
Cerrando por parecer arreglado.

**Comment by julienmalard** [comment]
Cerrando por parecer arreglado.
