### ISSUE TITLE
Problemas con cargar el modelo biophysico/ Problems when loading the biophysical model

### ISSUE THREAD

**Issue by SabineEgerer** [julienmalard/Tinamit#26]
**Describe el error**
Quiero cargar los modelos como en el ejemplo:
https://github.com/julienmalard/Tinamit/blob/master/README.rst
Pudeo cargar el modelo SD (en el forma .mdl) pero hay un error con el modelo BF

I tried to load the models like in the example given here:
https://github.com/julienmalard/Tinamit/blob/master/README.rst
I managed to load the SD model (using the format .mdl) but I get en error when loading the BF model.

Para reproducir:
```python:
modelo.estab_bf('Prueba bf.py')
```
Error:
```traceback:
Traceback (most recent call last):

  File "<ipython-input-43-aa3b49ba20d1>", line 1, in <module>
    modelo.estab_bf('Prueba bf.py')

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Conectado.py", line 924, in estab_bf
    modelo_bf = EnvolturaBF(modelo=bf)

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/BF.py", line 58, in __init__
    .format(modelo))

AttributeError: El archivo especificado ("Prueba bf.py") no contiene subclase de "ModeloBF".
```

**Información adicional**
Estoy trabajando en Linux, y uso Python 3.6, tinamit 2.0.
I'm working with Linux and use Python 3.6, tinamit 2.0.

Gracias por tu ayuda, thanks for your help,
Sabine

**Comment by julienmalard** [comment]
Hola,

Parece ser efectivamente error en Tinamït. Estoy trabajando en reproducirlo en mi compu y les aviso en cuanto lo arreglo.

Entre tiempo, veo que estás utilizando Anaconda...mi experiencia personal con Anaconda + Tinamït (¡y con Python en general!) ha sido bastante frustrante por varias razones. Si es posible recomendaría que empleen la distribución oficial de Python para trabajar con Tinamït.

¡Gracias!
-Julien

**Comment by julienmalard** [comment]
Ya se arregló con el cambio más recién. Si actualiza su instalación con otro pip install... debería funcionar.
¡Gracias!
